/*
Copyright (c) 2010 Hewlett-Packard Development Company, L.P. All rights reserved.
Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:
* Redistributions of source code must retain the above copyright
	notice, this list of conditions and the following disclaimer.
* Redistributions in binary form must reproduce the above
	copyright notice, this list of conditions and the following disclaimer
	in the documentation and/or other materials provided with the
	distribution.
* Neither the name of Hewlett-Packard nor the names of its
	contributors may be used to endorse or promote products derived from
	this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

static const char *pageCurlVertexSource = "#version 330 core\n"
	"layout (location = 0) in vec3 aPos;\n"
	"layout(location = 1) in vec2 aTexCoord;\n"
	"out vec2 texCoord;\n"
	"void main()\n"
	"{\n"
	"	texCoord = aTexCoord;\n"
	"	gl_Position = vec4(aPos, 1.0);\n"
	"}\0";

static const char *pageCurlFragmentSource = "#version 330 core\n"
	"out vec4 fragColor;\n"
	"in vec2 texCoord;\n"
	"uniform float progress;\n"
	"// texture samplers\n"
	"uniform sampler2D texture0;\n"
	"uniform sampler2D texture1;\n"
	"\n"
	"const float MIN_AMOUNT = -0.16;\n"
	"const float MAX_AMOUNT = 1.5;\n"
	"float amount = progress * (MAX_AMOUNT - MIN_AMOUNT) + MIN_AMOUNT;\n"
	"const float PI = 3.141592653589793;\n"
	"const float scale = 512.0;\n"
	"const float sharpness = 3.0;\n"
	"float cylinderCenter = amount;\n"
	"// 360 degrees * amount\n"
	"float cylinderAngle = 2.0 * PI * amount;\n"
	"const float cylinderRadius = 1.0 / PI / 2.0;\n"
	"\n"
	"vec3 hitPoint(float hitAngle, float yc, vec3 point, mat3 rrotation)\n"
	"{\n"
	"	float hitPoint = hitAngle / (2.0 * PI);\n"
	"	point.y = hitPoint;\n"
	"	return rrotation * point;\n"
	"}\n"
	"vec4 antiAlias(vec4 color1, vec4 color2, float distanc)\n"
	"{\n"
	"	distanc *= scale;\n"
	"	if (distanc < 0.0) return color2;\n"
	"	if (distanc > 2.0) return color1;\n"
	"	float dd = pow(1.0 - distanc / 2.0, sharpness);\n"
	"	return ((color2 - color1) * dd) + color1;\n"
	"}\n"
	"float distanceToEdge(vec3 point)\n"
	"{\n"
	"	float dx = abs(point.x > 0.5 ? 1.0 - point.x : point.x);\n"
	"	float dy = abs(point.y > 0.5 ? 1.0 - point.y : point.y);\n"
	"	if (point.x < 0.0) dx = -point.x;\n"
	"	if (point.x > 1.0) dx = point.x - 1.0;\n"
	"	if (point.y < 0.0) dy = -point.y;\n"
	"	if (point.y > 1.0) dy = point.y - 1.0;\n"
	"	if ((point.x < 0.0 || point.x > 1.0) && (point.y < 0.0 || point.y > 1.0)) return sqrt(dx * dx + dy * dy);\n"
	"	return min(dx, dy);\n"
	"}\n"
	"vec4 seeThrough(float yc, vec2 p, mat3 rotation, mat3 rrotation)\n"
	"{\n"
	"	float hitAngle = PI - (acos(yc / cylinderRadius) - cylinderAngle);\n"
	"	vec3 point = hitPoint(hitAngle, yc, rotation * vec3(p, 1.0), rrotation);\n"
	"	if (yc <= 0.0 && (point.x < 0.0 || point.y < 0.0 || point.x > 1.0 || point.y > 1.0))\n"
	"	{\n"
	"		return texture(texture1, p);\n"
	"	}\n"
	"\n"
	"	if (yc > 0.0) return texture(texture0, p);\n"
	"\n"
	"	vec4 color = texture(texture0, point.xy);\n"
	"	vec4 tcolor = vec4(0.0);\n"
	"\n"
	"	return antiAlias(color, tcolor, distanceToEdge(point));\n"
	"}\n"
	"vec4 seeThroughWithShadow(float yc, vec2 p, vec3 point, mat3 rotation, mat3 rrotation)\n"
	"{\n"
	"	float shadow = distanceToEdge(point) * 30.0;\n"
	"	shadow = (1.0 - shadow) / 3.0;\n"
	"\n"
	"	if (shadow < 0.0) shadow = 0.0; else shadow *= amount;\n"
	"\n"
	"	vec4 shadowColor = seeThrough(yc, p, rotation, rrotation);\n"
	"	shadowColor.r -= shadow;\n"
	"	shadowColor.g -= shadow;\n"
	"	shadowColor.b -= shadow;\n"
	"\n"
	"	return shadowColor;\n"
	"}\n"
	"vec4 backside(float yc, vec3 point)\n"
	"{\n"
	"	vec4 color = texture(texture0, point.xy);\n"
	"	float gray = (color.r + color.b + color.g) / 15.0;\n"
	"	gray += (8.0 / 10.0) * (pow(1.0 - abs(yc / cylinderRadius), 2.0 / 10.0) / 2.0 + (5.0 / 10.0));\n"
	"	color.rgb = vec3(gray);\n"
	"	return color;\n"
	"}\n"
	"vec4 behindSurface(vec2 p, float yc, vec3 point, mat3 rrotation)\n"
	"{\n"
	"	float shado = (1.0 - ((-cylinderRadius - yc) / amount * 7.0)) / 6.0;\n"
	"	shado *= 1.0 - abs(point.x - 0.5);\n"
	"\n"
	"	yc = (-cylinderRadius - cylinderRadius - yc);\n"
	"\n"
	"	float hitAngle = (acos(yc / cylinderRadius) + cylinderAngle) - PI;\n"
	"	point = hitPoint(hitAngle, yc, point, rrotation);\n"
	"\n"
	"	if (yc < 0.0 && point.x >= 0.0 && point.y >= 0.0 && point.x <= 1.0 && point.y <= 1.0 && (hitAngle < PI || amount > 0.5))\n"
	"	{\n"
	"		shado = 1.0 - (sqrt(pow(point.x - 0.5, 2.0) + pow(point.y - 0.5, 2.0)) / (71.0 / 100.0));\n"
	"		shado *= pow(-yc / cylinderRadius, 3.0);\n"
	"		shado *= 0.5;\n"
	"	}\n"
	"	else\n"
	"	{\n"
	"		shado = 0.0;\n"
	"	}\n"
	"	return vec4(texture(texture1, p).rgb - shado, 1.0);\n"
	"}\n"
	"\n"
	"void main()\n"
	"{\n"
	"	vec2 p = texCoord.xy;\n"
	"	const float angle = 100.0 * PI / 180.0;\n"
	"	float c = cos(-angle);\n"
	"	float s = sin(-angle);\n"
	"\n"
	"	mat3 rotation = mat3( c, s, 0,\n"
	"						-s, c, 0,\n"
	"						-0.801, 0.8900, 1\n"
	"						);\n"
	"	c = cos(angle);\n"
	"	s = sin(angle);\n"
	"\n"
	"	mat3 rrotation = mat3(  c, s, 0,\n"
	"						-s, c, 0,\n"
	"						0.98500, 0.985, 1\n"
	"						);\n"
	"\n"
	"	vec3 point = rotation * vec3(p, 1.0);\n"
	"\n"
	"	float yc = point.y - cylinderCenter;\n"
	"\n"
	"	if (yc < -cylinderRadius)\n"
	"	{\n"
	"		// Behind surface\n"
	"		fragColor = behindSurface(p, yc, point, rrotation);\n"
	"		return;\n"
	"	}\n"
	"\n"
	"	if (yc > cylinderRadius)\n"
	"	{\n"
	"		// Flat surface\n"
	"		fragColor = texture(texture0, p);\n"
	"		return;\n"
	"	}\n"
	"\n"
	"	float hitAngle = (acos(yc / cylinderRadius) + cylinderAngle) - PI;\n"
	"\n"
	"	float hitAngleMod = mod(hitAngle, 2.0 * PI);\n"
	"	if ((hitAngleMod > PI && amount < 0.5) || (hitAngleMod > PI/2.0 && amount < 0.0))\n"
	"	{\n"
	"		fragColor = seeThrough(yc, p, rotation, rrotation);\n"
	"		return;\n"
	"	}\n"
	"\n"
	"	point = hitPoint(hitAngle, yc, point, rrotation);\n"
	"\n"
	"	if (point.x < 0.0 || point.y < 0.0 || point.x > 1.0 || point.y > 1.0)\n"
	"	{\n"
	"		fragColor = seeThroughWithShadow(yc, p, point, rotation, rrotation);\n"
	"		return;\n"
	"	}\n"
	"\n"
	"	vec4 color = backside(yc, point);\n"
	"\n"
	"	vec4 otherColor;\n"
	"	if (yc < 0.0)\n"
	"	{\n"
	"		float shado = 1.0 - (sqrt(pow(point.x - 0.5, 2.0) + pow(point.y - 0.5, 2.0)) / 0.71);\n"
	"		shado *= pow(-yc / cylinderRadius, 3.0);\n"
	"		shado *= 0.5;\n"
	"		otherColor = vec4(0.0, 0.0, 0.0, shado);\n"
	"	}\n"
	"	else\n"
	"	{\n"
	"		otherColor = texture(texture0, p);\n"
	"	}\n"
	"\n"
	"	color = antiAlias(color, otherColor, cylinderRadius - abs(yc));\n"
	"\n"
	"	vec4 cl = seeThroughWithShadow(yc, p, point, rotation, rrotation);\n"
	"	float dist = distanceToEdge(point);\n"
	"	fragColor = antiAlias(color, cl, dist);\n"
	"}\0";